#template_file_name should be 'None' if no template is required in plugin
template_file_name: 'jsx_layout_temp.txt'
main_message_option_name: "FluxMsgJsonRoot"
output_file_name: "Layout.jsx"
insertion_import_file_name: "insertion_imports.py"
plugin_file_name: "jsx_layout_gen_plugin.py"
pb2_import_generator_path: "jsx_pb2_import_generator.py"
case_style: "snake" # snake or camel supported
